### ISSUE TITLE
Warn when there is a function called 'setup()'

### ISSUE THREAD

**Issue by maurelian** [gakonst/foundry#1167]
### Component

Forge

### Describe the feature you would like

This was a dumb mistake on my part, but it took me a while to get the proper capitalization of the `setUp()` function. 

It'd be nice if Forge would emit a warning or error when a test contract includes the incorrect of these two sigs:

```
0a9254e4: setUp() // Right
ba0bba40: setup() // Wrong
```

**Comment by onbjerg** [comment]
Three paths:

- We can emit a warning (as proposed)
- We can emit a warning, but run the setup anyway on any variation of `setUp` (e.g. `SETUP`, `seTup`, `setup` etc.)
- We can run the setup on any variation of `setUp` (as above), with no warning

Which would you prefer? Also cc @gakonst for thoughts on the same

**Comment by maurelian** [comment]
The last one makes sense to me.

**Comment by gakonst** [comment]
No warning and making it case insensitive makes sense

**Comment by claysauruswrecks** [comment]
@gakonst - Do we want to set the precedent of case-insensitivity? This shows there are two ways to do the same thing.

Do we stop here, or do we make other things case-insensitive as well? Are there other keywords we should make case-insensitive also? Which way should be presented in the docs?

**Comment by gakonst** [comment]
All good questions, do we have something else which is case sensitive?

**Comment by claysauruswrecks** [comment]
@gakonst - I'm still getting familiar with the codebase, so IDK.

I'm coming from Python unittest, and they utilize `setUp` and `setUpClass`. JS frameworks also use `setUp` from what I've seen. Technically `setup` is 1 word as a noun, but `set up` is 2 words as a verb or w/e that thing is called in English.

I would expect the framework to follow Solidity conventions for functions names in Solidity code: https://docs.soliditylang.org/en/latest/style-guide.html#function-names

Another option is to keep with community momentum with Truffle's `beforeEach` instead of `setUp`.

Whichever way, we should probably aim for consistency, less confusion, and aligning with mental momentum from other frameworks for onboarding engineers.

**Comment by onbjerg** [comment]
We use `setUp` for DappTools compatibility, so we probably won't change that in the near future. I don't think anything else should be case insensitive
