### ISSUE TITLE
forge verify-contract should check that the contract is within the project `src` directory

### ISSUE THREAD

**Issue by prestwich** [gakonst/foundry#1251]
### Component

Forge

### Describe the feature you would like

`verify-contract` does not check that the contract path argument is within the project's configured `src` directory. If the contract is outside that directory, it will fail with a misleading error.

Misleading error
```
Error: 
   0: Failed to get standard json input: cannot resolve file at ""/path/to/actual/contract/location/Contract.sol""
```

Instead, `verify_contract` should check that the path has the project `src` dir as a prefix, and inform the user if it is outside

Desired behavior:
```
Error:
   0: Contract "/path/to/actual/contract/location/Contract.sol" is outside of project source directory "/path/to/foundry/expected/src/
```

Note that the doubled `""...""` is due to escaped quotes in the underlying ethers-solc error message :)

**Comment by rpollock** [comment]
I was still getting this issue!

before i was using yarn verify --network sepolia

then i was using the path within my directory in my foundry.toml file

the best way to resolve this issue is to go to your terminal 

```powershell
forge verify-contract --network <whatever network youve deployed your contract on> <Contract address> 
``` 

then press tab and it will show you the list of folders or files and you can avoid this issue by putting in the right path, and make sure you put your contract name at the end!

heres my command 

```powershell
forge verify-contract --chain sepolia 0x97338781a241D7C4432b017e666Ee76bed0b122e contracts/Multisend.sol:Multisend
```
