### ISSUE TITLE
Forge test only running tests every other invocation

### ISSUE THREAD

**Issue by alcibiadeseth** [gakonst/foundry#170]
```Athens % forge test
success.
Athens % forge test
success.
Running 1 test for ContractTest
[PASS] testExample (gas: 254)

**Comment by mattsse** [comment]
this is likely an ethers-solc caching issue, this has come up but not yet pinned down, if you could share what `tree -d contracts` looks like, that be helpful.

**Comment by alcibiadeseth** [comment]
```tree -d yapeswap
yapeswap
├── cache
├── lib
│   └── ds-test
│       ├── demo
│       └── src
├── out
│   ├── IERC20.sol
│   ├── IUniswapV2Callee.sol
│   ├── IUniswapV2ERC20.sol
│   ├── IUniswapV2Factory.sol
│   ├── IUniswapV2Pair.sol
│   ├── Math.sol
│   ├── SafeMath.sol
│   ├── Sqrt.sol
│   ├── UQ112x112.sol
│   ├── UniswapV2ERC20.sol
│   ├── UniswapV2Factory.sol
│   ├── UniswapV2Pair.sol
│   ├── Fork.t.sol
│   └── test.sol
└── src
    ├── interfaces
    ├── libraries
    └── test

24 directories```

**Comment by alcibiadeseth** [comment]
This seems resolved after installing with `--locked`.

**Comment by alcibiadeseth** [comment]
Hmm, never mind, still seeing this.

**Comment by mattsse** [comment]
thanks, It looks like all contract artifacts are generated correctly into `out`, right?
but only `test/ContractTest` is executed?

**Comment by gakonst** [comment]
Maybe addressed in https://github.com/gakonst/ethers-rs/pull/623, will try it out

**Comment by gakonst** [comment]
I think this should be fixed since updating to [latest ethers master](https://github.com/gakonst/foundry/commit/831cc387568de15b0b47df05b01e0d54b305b2c5) and fixing the compilation bugs upstream https://github.com/gakonst/ethers-rs/pull/623, https://github.com/gakonst/ethers-rs/pull/629, https://github.com/gakonst/ethers-rs/pull/630.

Closing optimistically, feel free to re-open if still an issue.
