### ISSUE TITLE
unexpected character error

### ISSUE THREAD

**Issue by wighawag** [gakonst/foundry#254]
executing this:

`forge build --lib-paths node_modules`

I get 

```
compiling...
Dec 18 15:43:57.198 ERROR forge: error=unexpected character ',' while parsing major version number
Error:
   0: unexpected character ',' while parsing major version number

Location:
   /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1914

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 5 frames hidden ⋮
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual::ha63865f195437062
      at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1914
   7: <forge::cmd::build::BuildArgs as forge::cmd::Cmd>::run::hcea70d2bba785fed
      at /home/wighawag/.cargo/git/checkouts/foundry-f45668fa08523154/d4de7c8/cli/src/cmd/build.rs:86
        84 │         println!("compiling...");
        85 │         let project = self.project()?;
        86 >         let output = project.compile()?;
        87 │         if output.has_compiler_errors() {
        88 │             // return the diagnostics error back to the user.
   8: forge::main::{{closure}}::hbc43f40781e43c6e
      at /home/wighawag/.cargo/git/checkouts/foundry-f45668fa08523154/d4de7c8/cli/src/forge.rs:24
        22 │         }
        23 │         Subcommands::Build(cmd) => {
        24 >             cmd.run()?;
        25 │         }
        26 │         Subcommands::VerifyContract { contract, address, constructor_args } => {
   9: forge::main::hc77be802898065f2
      at /home/wighawag/.cargo/git/checkouts/foundry-f45668fa08523154/d4de7c8/cli/src/forge.rs:13
        11 │
        12 │ #[tracing::instrument(err)]
        13 > fn main() -> eyre::Result<()> {
        14 │     color_eyre::install()?;
        15 │     utils::subscriber();
  10: core::ops::function::FnOnce::call_once::h125a34c6b9898adb
      at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227
                                ⋮ 4 frames hidden ⋮

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

I perform the operation in this repo : https://github.com/wighawag/jolly-roger

in the `contracts` folder

This folder contains a dapptools setup and `dapp test` run fine there

**Comment by mattsse** [comment]
Thanks for this, this will help us improve hardhat support.

couple things are happening here:

1. if no `--root` path is provided then forge chooses the git root over the current dir, perhaps that can be counterintuitive? ad `--root .` to make the nested `contracts` dir the root
2. hardhat remappings are currently not auto-detected properly, so you'd need to provide them as `--remappings hardhat/=node_modules/hardhat/ hardhat-deploy/=node_modules/hardhat-deploy/`, this will become obsolete shortly
3. apparently solc's `--allow-paths` does not work recursively? so that `solc --allow-paths node_modules` does not give solc access to `node_modules/hardhat` instead it has to be `--allow-paths node_modules/hardhat,node_modules/hardhat-deploy`...

you can get all of this to work with 
`forge build --lib-paths node_modules node_modules/hardhat node_modules/hardhat-deploy --root . --remappings hardhat/=node_modules/hardhat/ hardhat-deploy/=node_modules/hardhat-deploy/`
which is of course far from ideal, but not that we have a couple of examples, expect that work with `forge build` or `forge build --root .` only

cc @gakonst

**Comment by gakonst** [comment]
Maybe we can make the --hardhat be an alias for the commands line args above?

**Comment by wighawag** [comment]
Thanks @mattsse and @gakonst for your quick replies.

I ll try these suggestion. notice the dapprc file here : https://github.com/wighawag/jolly-roger/blob/main/contracts/.dapprc

I think a config file would be great for foundry/forge but it would also be cool if supported dapprc as fallback (though I am not sure I really need that long term)

**Comment by gakonst** [comment]
There's a `--hh` command available now in master, can you try with that? Also until we have full support for loading env vars from a config file, you can always do `. .dapprc && forge test`

**Comment by wighawag** [comment]
Nice! `forge test --hh --root .`  works like a charm
Thanks

**Comment by gakonst** [comment]
Was the `--root .` needed?

**Comment by mattsse** [comment]
> Great to hear! Was the `--root .` needed?

We currently prioritize the git root over the working dir

https://github.com/gakonst/foundry/blob/2bd51d633d90d4599994ccbd96bb8676b68ea185/cli/src/cmd/build.rs#L153

so in order to runt forge in

```console
jolly-roger
├── contracts

```

the root option is needed to set root to `contracts`, but I wonder if we should default to cwd instead?

**Comment by gakonst** [comment]
Hmm this is rough. The reason why we prioritize the git root is that if you're in a subdirectory (e.g. under `src/`) you still want to be able to do `forge test` and have the tests run. If we had `forge.toml` we could find the project root that way, so let's keep the behavior as-is and use the path of the forge.toml (when we add it) as the repo root.
