### ISSUE TITLE
feat: `vm.assume` cheat code for discarding bad fuzz inputs

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#286]
Named after Hypothesis' [`assume`](https://hypothesis.readthedocs.io/en/latest/details.html#making-assumptions), this cheat code would let you mark fuzzer inputs as invalid. Invalid fuzz runs are not counted toward the number of executed runs, so new inputs would be generated and the test re-ran

Use cases:
- Ensure conditions on fuzzer inputs are met, such as "don't test the zero address" or "make sure `x + y < z`". 
- Bound inputs to a range: For this use case it's likely much faster to just [manually](https://github.com/Rari-Capital/solmate/blob/ce02b34f83e756852d1b1a036223b050e284ab29/src/test/utils/DSTestPlus.sol#L102-L121) wrap values into the desired range. However, if foundry ever supports generating fuzz statistics / saving fuzz inputs, foundry would not know about manual bounding so `assume` may become preferable to ensure more useful statistics/outputs

Depending on the condition you pass in, it might take a long time to get enough valid fuzz runs for your test to complete, so ideally this method can be "smart" and learn from failed assumptions similar to what Hypothesis does. Hypothesis' `assume` method uses an "adaptive exploration [strategy](https://hypothesis.readthedocs.io/en/latest/details.html#how-good-is-assume)", to do this, and I believe the implementation of that strategy is [here](https://github.com/HypothesisWorks/hypothesis/blob/09e5035edbb68fafb1012c0e910da31d1bc3b370/hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py#L959-L999)

```solidity
interface Vm {
  // If the input is false, mark this fuzz run as invalid and generate a new set if inputs
  function assume(bool) external;
}
```

**Comment by gakonst** [comment]
`prop_assume!` is part of the crate we use (proptest), so it might be a simple matter of calling it when the `vm.assume` call is made.

Need to think about how to implement this, because the cheatcode logic in `cheatcode_handler.rs` is very separate from the fuzzer logic in `fuzz.rs` in `evm-adapters`..

Extra info:
* https://github.com/AltSysrq/proptest/blob/bc2d867a7cd06060e0b565b72fce1d94cc2fe943/proptest/src/sugar.rs#L250-L261
* https://github.com/AltSysrq/proptest/blob/master/book/src/proptest/tutorial/filtering.md

**Comment by mds1** [comment]
closing in favor of https://github.com/gakonst/foundry/issues/387 to consolidate all fuzzer discussion
