### ISSUE TITLE
Build error double print

### ISSUE THREAD

**Issue by odyslam** [gakonst/foundry#303]
I think that `forge build` doesn't gracefully handle the error produced by `solc`. It should not produce a `forge` error and return stack trace, but rather surface the `solc` error and gracefully exit. 

Using the latest version of forge.

![image](https://user-images.githubusercontent.com/13405632/147363905-103ca954-2e28-4a24-b2b6-b29b393253a9.png)

**Comment by mattsse** [comment]
I believe this due to the eyre hook because we currently "panic" on erroneous solc output.
instead, we should, as you suggested exit gracefully with std::process::exit(1)

here
https://github.com/gakonst/foundry/blob/8c234f75937d7cd06f6101fc298fe36da369ca44/cli/src/forge.rs#L24

or here
https://github.com/gakonst/foundry/blob/8c234f75937d7cd06f6101fc298fe36da369ca44/cli/src/cmd/build.rs#L84-L97

ideally there should be two versions of `Build::run`, one that `std::process:exits` and one that we can reuse anywhere else which returns the error instead of exiting
