### ISSUE TITLE
`forge init` should fail if the current working directory isn't empty

### ISSUE THREAD

**Issue by SamWilsn** [gakonst/foundry#460]
I ran `forge init` with no arguments in my `~/Code` directory, and it made a new git repository that recommended adding all my unrelated projects as submodules.

`forge init` should probably fail to run in a non-empty directory, unless a `--force` option (or similar) is given.

**Comment by mattsse** [comment]
hmm, I think it should still if for example the dir already contains a README or license etc.

But yeah the problem is that we do a blind `git add .` which also adds inner repos, we should scan nested existing dirs (not called `lib`) and fail with we encounter a git repo


worth having a look at `cargo init`

https://github.com/rust-lang/cargo/blob/06b9d31743210b788b130c8a484c2838afa6fc27/src/cargo/ops/cargo_new.rs#L721-L731

also suggesting some flags for init

`--no-vcs` or `--no-git` to not initialize a new git repo.
`-q, --quite` to not print anything
`--offline` do not pull anything from network (ds-test, forge-std)

**Comment by SamWilsn** [comment]
I think the simplest option (just fail if the directory is non-empty) is probably good enough to cover 80% of cases. If someone really wants to `init` a non-empty directory, `--force` would unblock them.

**Comment by Mikerah** [comment]
I know this is a closed issue but using `--force` ends up overwriting the contents of the directory even though there are times when the directory has already been setup as a git project and it just needs the forge portions setup. Perhaps, there can be an option to add the forge related directories to an already existing git project.
