### ISSUE TITLE
`forge test --watch` becomes `forge build --watch` if you edit a non test file

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#847]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (2ff2b33 2022-03-05T23:33:56.682578+00:00)

### What command(s) is the bug in?

forge test --watch

### Operating System

macOS (M1)

### Describe the bug

`forge test --watch` works super well up until you edit a non .t.sol file

then saving again even if the build succeeds won't run the tests, it will just say compilation passed (like what would happen if you just ran `forge build --watch`)

**Comment by transmissions11** [comment]
hmm wait i'm not really sure what causes this behavior, seems to happen in other cases as well...

**Comment by transmissions11** [comment]
oh ok i think it happens not if the build fails but if you make a change **thats not in a test file**

**Comment by mattsse** [comment]
I was wondering what the ideal behavior would be in such cases.

Here's how --watch works rn:

we take the whole command minus the `--watch` arg: `forge test <args>` and listen for file changes to then add a `--match-path <changed file>` argument before running the command again

This approach works perfectly fine until a file without a test is changed because then `--match-path <file>` contains a file without any tests, hence it's just `forge build`

however, if watch mode was initially started with `forge test (--match-test|--match-path)` then we don't adjust the path and run the command as is.

I was wondering if in that case we should run the latest `.t.sol` file if a non `.t.sol` was changed, but this is a bit opinionated and could cause some confusion.

Or should we simply don't adjust the path arg at all und just run the command as it was provided

**Comment by transmissions11** [comment]
> I was wondering if in your scenario we should run the latest .t.sol file if a non .t.sol was changed, but this is a bit opinionated and could cause some confusion.

i think this is the most sensical option, and the behavior i would strongly prefer

ie: for things like TDD

**Comment by transmissions11** [comment]
also btw i was still experiencing this issue with `--match-contract` as a flag

to be exact i was running:

```
forge test -w --match-contract SafeTransferLibTest -vvv 
```

**Comment by transmissions11** [comment]
hmm that PR seemed to make things worse? after running foundryup i cant get the test watch mode to work at all? it just always compiles without running tests

**Comment by transmissions11** [comment]
er nvm its just a bit finnicky. the "Compiling X files with 0.8.X" text could use a loader to make it clear something is happening

**Comment by transmissions11** [comment]
ok the one way things do work unexpectedly for me is if i use `--match-contract SafeTransferLibTest` and then edit another test it will revert back to just doing builds unless i go and edit `SafeTransferLibTest` again. ideally it would just remember the contract im matching and always run that in watch mode

**Comment by transmissions11** [comment]
also since we've gone with the fairly opinionated route of only running the last edited test in watch mode, might be nice to add the ability to just run all tests every time behind a flag like `--run--all`, as i can imagine some cases where that's useful

**Comment by mattsse** [comment]
All good points, thanks!
will get this included!

> er nvm its just a bit finnicky. the "Compiling X files with 0.8.X" text could use a loader to make it clear something is happening

like some spinning cursor? that'd be nice

**Comment by transmissions11** [comment]
> like some spinning cursor? that'd be nice

yup exactly
