### ISSUE TITLE
Maintain a docker image for latest foundry release

### ISSUE THREAD

**Issue by abdulrabbani00** [gakonst/foundry#907]
### Component

Foundryup

### Describe the feature you would like

It would be wonderful if the team maintained an image of the latest version of foundry. I will be working on creating a process to create such an image. I would be more than happy to provide the code for this task if the team would be interested in publishing and maintaining the image.

**Comment by gakonst** [comment]
Would be open to integrating it in our release process!

**Comment by mattsse** [comment]
I guess what we need for this is:

- [ ] Dockerfile that installs forge (and use forge as entrypoint)
- [ ] a docker.yml action, like https://github.com/docker/build-push-action that publishes to ghcr.io registry

**Comment by abdulrabbani00** [comment]
@gakonst @mattsse - I would be more than happy to provide a Dockerfile that installs foundry. If I opened a PR with the file, would your team be able to integrate it maintain a build with the latest version on docker hub?

**Comment by gakonst** [comment]
If you'd be down to also provide a Gihtub Action that publishes to Dockerhub, we can take care of credentials etc!

**Comment by abdulrabbani00** [comment]
That's perfect. Do you guys have a preferred base image? Otherwise, I can simply use Alpine and perform the installs as the root user.

**Comment by gakonst** [comment]
Alpine SGTM!

**Comment by abdulrabbani00** [comment]
@gakonst - I have created the following [PR](https://github.com/gakonst/foundry/pull/914). Alpine was giving me too many troubles when attempting to run `cast` and `forge` due to system dependencies. I also noticed some errors with `GLIBC` on `Centos` (`forge` requires version `2.29` and `centos` is only up to `2.28`). I decided to go with `debian` and everything works fine.

A quick note on testing:
* Prior to merging to master, I highly recommend manually running the pipeline to ensure that it publishes to dockerhub correctly.
* You might need to update the `LABEL` in the `Dockerfile` as well as the `tag` in GHA to make everything work correctly.

I hope this can get merged by Monday so I can use it in my current project :)

Thanks a lot, I am also currently working on running geth on a private network. This is a feature I am integrating from `dapptools`, I would be more than happy to discuss this with you guys and see if there is any interest in adding a "tools" section to foundry.

- Cheers :)

**Comment by dmfxyz** [comment]
Hi everyone. I think getting Foundry in docker would be really helpful for both myself and others. Pushing forward off of was built by others in #914 and #981 , I've made good progress in building a fully functioning, alpine based Foundry image. I think we should clarify next steps here in the issue rather than the pr.

Here's what we have:
- A Dockerfile that builds foundry from scratch on alpine: https://github.com/dmfxyz/foundry/blob/dockerize/Dockerfile. I have a build hosted in [ghcr right now](https://github.com/dmfxyz/foundry/pkgs/container/foundry/17170188?tag=dockerize). Final compressed image size is 20.9MB, pretty good IMO. Extracted is 42.9MB. 

- A github action that can cross build docker images for all architectures (currently just amd64 to save testing time): https://github.com/dmfxyz/foundry/blob/dockerize/.github/workflows/docker-publish.yml. The image is also signed.

Here's some open questions/issues

- I want to confirm there is still agreement among maintainers and community that we want a Docker image?

- How should this be incorporated into CI/CD? I tend to agree with what was suggested in #914 by @onbjerg and have the release workflow call out to the multi-architecture build job I linked above.

- The image will not build natively on neither Intel nor M1 macs based on my testing. I've THINK I narrowed it down to some libusb dependencies which are not able to be built because macos doesn't natively have libusb, and the brew install doesn't play nice with Docker (let me stress this is just a theory, it's a real rabbit hole). **_Good news is that an image built on, say, Ubuntu or some other *nix seems to run perfectly on both intel and m1 macs_** (I've tested on the two I own). In my experience this is a classic issue with building alpine based docker images on macos. Unless there are serious concerns with this, I don't think it's a first-release blocker as the release image will not be built on macos anyway. It is tech debt though. 

@gakonst @onbjerg @tynes @mattsse when you guys have time (I know there's a lot going on right now) please share your thoughts here. I'll get everything working as I have now, and then happy to put it on ice until we have time to answer the above. 

Many thanks to @abdulrabbani00 for getting this started.

**Comment by gakonst** [comment]
> I want to confirm there is still agreement among maintainers and community that we want a Docker image?

Yes! 

+1 on Bjerg suggestion re: CI

**Comment by abdulrabbani00** [comment]
@dmfxyz - Great work. I strongly agree with your approach. Let's get something working in the container registry so people can start using it. Really appreciate you taking charge here and bringing it home :D

**Comment by dmfxyz** [comment]
Pipeline for releases in PR: https://github.com/gakonst/foundry/pull/1065

**Comment by sambacha** [comment]
> * The image will not build natively on neither Intel nor M1 macs based on my testing. I've THINK I narrowed it down to some libusb dependencies which are not able to be built because macos doesn't natively have libusb, and the brew

how many times is this going to come up, please @gakonst make this a flag on build. how many users even use this feature? I

**Comment by gakonst** [comment]
@sambacha It is a flag already... https://github.com/gakonst/foundry/blob/master/cast/Cargo.toml#L23

**Comment by sambacha** [comment]
> @sambacha It is a flag already... https://github.com/gakonst/foundry/blob/master/cast/Cargo.toml#L23. If you have a better way to do this, you're welcome to open a PR ;)

its a full time job trying to stay up to date with changes here can you blame me? 

However when you build only forge, it still is using the crate evidently in the build process
