### ISSUE TITLE
Recompiling on every `forge test` run

### ISSUE THREAD

**Issue by leeren** [gakonst/foundry#941]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

Runs of `forge test` cause contract recompilation of the same 18/63 contracts on every invocation.

[Contract Repo](https://github.com/DopamineDAO/dopamine-contracts)

**Comment by mattsse** [comment]
thanks for this.

master currently does not compile due to undeclared NUM_WHITELIST DompaninPass.sol and wrong constructor call in the corresponding test.

however I've managed to compile it successfully after minor modifications.

I could reproduce this with `forge test`, interestingly forge build skips recompile.
