### ISSUE TITLE
Support test path outside of src directory

### ISSUE THREAD

**Issue by ecmendenhall** [gakonst/foundry#970]
### Component

Forge

### Describe the feature you would like

Forge implicitly assumes the configured `test` path is a subdirectory of the configured `src` path. It would be helpful if it supported any directory in the project path.

I'm introducing forge and ds-test to a Hardhat project with an existing test suite, and I'd like to keep all the tests in one place. The Hardhat convention is a top level `/test` directory. 

### Additional context

Here's a [minimal example](https://github.com/ecmendenhall/foundry-test-path). This is an out of the box Hardhat project, plus `foundry.toml` and two DSTest examples.

**Comment by mattsse** [comment]
this is rather a ethers-solc issue, 
I wonder why this is not supported, because we already include the test folder when reading all sources:

https://github.com/gakonst/ethers-rs/blob/fab30887a2373d260d41689e71242ce0ac979c80/ethers-solc/src/config.rs#L90-L101

which is called here https://github.com/gakonst/ethers-rs/blob/master/ethers-solc/src/lib.rs#L208

and the test folder should be "test" by default, hmm

> Forge implicitly assumes the configured test path is a subdirectory of the configured src path. 

I not sure about this, but it could be that we're not setting the tests folder correctly in the `config` crate when the `ProjectPathsConfig` is created.

hopefully this is enough context, lmk if smth is unclear
